<?php

// $Id$

/**
 * @file
 * Allows selection of a primary term for nodes
 */
 
/**
 * Implementation of hook_nodeapi().
 */

function primary_term_nodeapi(&$node, $op, $teaser, $page) {
  // This module sets $node->primary_term on node load but
  // $node->primaryterm via the node form.  I don't know if a previous
  // author meant that or if it was a mistake.  For now, the module
  // preserves that behavior.

  switch ($op) {
    case 'presave':
      // Make sure the PT is assigned to the node as a normal term.
      //
      // taxonomy_node_save() allows $node->taxonomy to contain tids,
      // term objects, or arrays of tids (keyed by vocabulary).  So,
      // we can add the PT tid to the end of the array.
      //
      // However, taxonomy_node_save() assumes that a given tid only
      // occurs once anywhere in node->taxonomy(), so we have to make
      // sure the PT tid is not already assigned via the form to this
      // node before adding it.
      //
      // In the end, this is more work than doing it "wrong" during
      // insert/update.
      if (!empty($node->primaryterm)) {
        $tid = $node->primaryterm;
      } 
      elseif (!empty($node->primary_term)) {
        $tid = $node->primary_term->tid;
      }
      
      if (!empty($tid)) {
        foreach ($node->taxonomy as $k => $v) {
          if (is_object($v) && $v->tid == $tid) {
            return;
          } 
          elseif (is_array($v) && !empty($v[$tid])) {
            return;
          }
          elseif (is_numeric($v) && $v == $tid) {
            return;
          }
        }
        
        $node->taxonomy[] = $tid;
        
        // Load the term so it's available to token/pathauto
        $node->primary_term = taxonomy_get_term($tid);
      }
      break;

    case 'insert':
    case 'update':
      db_query('DELETE FROM {primary_term} WHERE vid = %d', $node->vid); // only one term per node revision
      // When node form is submitted, the new PT tid comes in as
      // $node->primaryterm (because it is set as
      // $form['taxonomy']['primaryterm'] but with #tree => false.  If
      // it is comes directly from node_load(), the PT term object is
      // in $node->primary_term.
      if (!empty($node->primaryterm)) {
        $primaryterm = $node->primaryterm;
      } 
      elseif (!empty($node->primary_term)) {
        $primaryterm = $node->primary_term->tid;
      }
      
      if (empty($primaryterm)) {
        break;
      }

      db_query('INSERT INTO {primary_term} (vid, tid) VALUES (%d, %d)', $node->vid, $primaryterm);
      break;

    case 'load':
      $tid = db_result(db_query('SELECT tid FROM {primary_term} WHERE vid = %d', $node->vid));
      if ($tid && $term = taxonomy_get_term($tid)) {
        $node->primaryterm = $tid;
        $node->primary_term = $term;
      }
      break;

    case 'view':
      if (module_exists('context') && $page) {
        $object = menu_get_object();
        if (isset($object->nid) && $object->nid === $node->nid) {
          if ($plugin = context_get_plugin('condition', 'primary_term')) {
            $plugin->execute($node, 'view');
          }
        }
      }
      break;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function primary_term_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] .'_node_form' == $form_id) {
    $node_type = $form['type']['#value'];
    $node = $form['#node'];

    if ($vids = variable_get('pt_vocabs_'. $node_type, array())) {
      // Build the select list options from the terms within these vocabularies.
      $options = array();
      foreach ($vids as $vid) {
        if (primary_term_vocabulary_access($vid)) {
          if ($tree = taxonomy_get_tree($vid)) {
            // If i18n Taxonomy is installed, localize the names of the terms we are fetching.
            if (module_exists('i18ntaxonomy')) {
              $tree = i18ntaxonomy_localize_terms($tree);
            }

            foreach ($tree as $term) {
              $options[$term->tid] = str_repeat('-', $term->depth) .' '. $term->name;
            }
          }
        }
      }

      $default_value = array();
      if (isset($node->primaryterm)) {
        $default_value = $node->primaryterm;
      }

      // if the primary term is not required, we add the option to ignore it
      $required = variable_get('pt_required_'. $node_type, FALSE);
      if (!$required) {
        // avoid reindexing of the array
        $options = array(t('- None -')) + $options;
      }

      $form['primaryterm'] = array(
        '#type' => 'select',
        '#title' => variable_get('pt_title_'. $node_type, t('Primary term')),
        '#description' => t('Select a primary term for this %type.', array('%type' => $node_type)),
        '#options' => $options,
        '#default_value' => $default_value,
        '#required' => $required,
        '#theme' => 'taxonomy_term_select',
      );

      if (module_exists('content')) {
        $form['primaryterm']['#weight'] = content_extra_field_weight($node_type, 'primary_term');
      }
    }
  }
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function primary_term_form_node_type_form_alter(&$form, &$form_state) {
  $node_type = $form['old_type']['#value'];
  $vocabularies = taxonomy_get_vocabularies($node_type);

  $options = array();
  foreach ($vocabularies as $vocabulary) {
    $options[$vocabulary->vid] = $vocabulary->name;
  }

  $form['workflow']['pt_vocabs'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Primary term vocabularies'),
    '#options' => $options,
    '#default_value' => variable_get('pt_vocabs_'. $node_type, array()),
    '#description' => t('Select which vocabularies should contribute terms to the primary term selector. Select none and the selector will not appear.'),
  );
  $form['workflow']['pt_required'] = array(
    '#type' => 'checkbox',
    '#title' => t('Primary term is required'),
    '#default_value' => variable_get('pt_required_'. $node_type, FALSE),
    '#description' => t('Select whether a primary term is required for this node type.'),
  );
  $form['workflow']['pt_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Primary term widget label'),
    '#required' => TRUE,
    '#default_value' => variable_get('pt_title_'. $node_type, t('Primary Term')),
    '#description' => t("Enter a label for the primary term widget."),
  );

  $form['#validate'][] = 'primary_term_node_type_form_validate';
}

/**
 * Validate our changes to the node_type_form.
 */
function primary_term_node_type_form_validate(&$form, &$form_state) {
  // Verify that if the Primary Term is required, there is a vocabulary
  // associated with it.
  if (($form_state['values']['pt_required']) && !in_array(TRUE, $form_state['values']['pt_vocabs'])) {
    form_set_error('pt_required',t('If you choose to make the Primary Term required, you must select at least one vocabulary for it.'));
  }
}

/**
 * Get primary term for a given node version id (vid)
 *
 * @param integer $vid
 */
function primary_term_get_term($vid) {
  return db_result(db_query('SELECT tid FROM {primary_term} WHERE vid = %d', $vid));
}

/**
 * Check permission to access the vocabulary with the given vid.
 *
 * Currently used to add support for taxonomy_role.
 *
 * @param $vid The vocabulary id of the vocab we are checking access for.
 *
 * @return boolean TRUE if the current user can view this vocabulary.
 */
function primary_term_vocabulary_access($vid) {
  // If taxonomy_role is not enabled, return early.
  if (!module_exists('taxonomy_role')) {
    return TRUE;
  }

  $vocabularies = taxonomy_get_vocabularies();
  if (is_numeric($vid) && user_access('access '. check_plain($vocabularies[$vid]->name) .' vocabulary')) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Implementation of hook_content_extra_fields().
 */
function primary_term_content_extra_fields() {
  $extras = array();

  $extras['primary_term'] = array(
    'label' => t('Primary Term'),
    'description' => t('Primary term widget (node editing only)'),
    'weight' => 0,
  );

  return $extras;
}

/**
 * Token support
 */

/**
 * Implementation of hook_token_list().
 */
function primary_term_token_list($type = 'all') {
  if ($type == 'node' || $type == 'all') {
    $tokens['node']['primary-term'] = t('Name of primary term');
    $tokens['node']['primary-term-id'] = t('ID of primary term');
    $tokens['node']['primary-termpath-raw'] = t('Full Path to Primary Term');
    $tokens['node']['primary-term-vocab'] = t('Name of the vocab of primary term');

  if (module_exists('uc_catalog')) {
    $tokens['node']['primary-termpath-uc-raw'] = t('Full catalog path to Primary Term');
  }

    return $tokens;
  }
}

/**
 * Implementation of hook_token_values().
 */
function primary_term_token_values($type, $object = NULL) {
  $values = array();

  switch ($type) {
    case 'node':
      $node = $object;
      if (isset($node->primaryterm) && $node->primaryterm > 0) {
        $term = taxonomy_get_term($node->primaryterm);
        $values['primary-term'] = check_plain($term->name);
        $values['primary-term-id'] = $term->tid;
        $values['primary-termpath-raw'] = drupal_get_path_alias(taxonomy_term_path($term));

        $vocab = taxonomy_vocabulary_load($term->vid);
        $values['primary-term-vocab'] = $vocab->name;

        if (module_exists('uc_catalog')) {
          $values['primary-termpath-uc-raw'] = drupal_get_path_alias(uc_catalog_path($term));
        }
      }
      break;
  }
  return $values;
}

/**
 * Views support
 */

/**
 * Implementation of hook_views_api().
 */
function primary_term_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'primary_term') . '/includes/views',
  );
}

/**
 * CTools support
 */

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * mypane/panels are used.
 */
function primary_term_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Context support
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function primary_term_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implementation of hook_context_plugins().
 */
function primary_term_context_plugins() {
  $plugins = array();
  $plugins['primary_term_context_condition_primary_term'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'primary_term') . '/plugins/context',
      'file' => 'primary_term_context_condition_primary_term.inc',
      'class' => 'primary_term_context_condition_primary_term',
      'parent' => 'context_condition_node',
    ),
  );
  return $plugins;
}

/**
 * Implementation of hook_context_registry().
 */
function primary_term_context_registry() {
  return array(
    'conditions' => array(
      'primary_term' => array(
        'title' => t('Primary Term'),
        'plugin' => 'primary_term_context_condition_primary_term',
      ),
    ),
  );
}
